name: Clang

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'LUA_LICENSE'
      - 'logo.png'
      - 'doc/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'LUA_LICENSE'
      - 'logo.png'
      - 'doc/**'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux Clang Debug",
            os: ubuntu-latest,
            build_type: "Debug",
            cc: "clang",
            cxx: "clang++"
          }
        - {
            name: "Linux Clang Release",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "clang",
            cxx: "clang++"
          }
    steps:
      - uses: actions/checkout@v3

      - name: Install clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15

      - name: Build
        shell: bash
        env:
          BUILD_TYPE: ${{ matrix.config.build_type }}
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          cmake --preset=clang -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=OFF
          cd ./build
          make

      - name: Install
        shell: bash
        working-directory: ./build
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          sudo make install

      - name: Clean
        shell: bash
        run: |
          rm -rf ./build

      - name: Test
        shell: bash
        working-directory: ./test
        env:
          BUILD_TYPE: ${{ matrix.config.build_type }}
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          cmake --preset=clang -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=OFF
          cd ./build
          make
